# Generated by Django 5.0.7 on 2024-08-20 18:33

import invoice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('work_order', models.IntegerField(unique=True)),
                ('invoice_number', models.CharField(max_length=10, null=True, unique=True, validators=[invoice.models.validate_invoice_number])),
            ],
        ),
    ]
