# Generated by Django 5.0.7 on 2024-08-18 19:08

import invoice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(unique=True, validators=[invoice.models.validate_invoice_number]),
        ),
    ]
