# Generated by Django 5.0.7 on 2024-08-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='work_order',
            field=models.IntegerField(),
        ),
    ]
