# Generated by Django 5.0.7 on 2024-08-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='note',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='work_order',
            field=models.IntegerField(unique=True),
        ),
    ]
