# Generated by Django 5.0.7 on 2024-08-20 03:29

import invoice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_remove_invoice_note_alter_invoice_work_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(null=True, unique=True, validators=[invoice.models.validate_invoice_number]),
        ),
    ]
