# Generated by Django 5.0.7 on 2024-08-20 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
    ]
