# Generated by Django 5.0.7 on 2024-08-20 03:50

import invoice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(validators=[invoice.models.validate_invoice_number]),
        ),
    ]
