# Generated by Django 5.0.7 on 2024-07-27 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0002_alter_sparepart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.customer')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.payment')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_work', models.CharField(choices=[('Maintenance', 'Maintenance'), ('Engine Repair', 'Engine Repair'), ('Transmission Repair', 'Transmission Repair'), ('Body and Painting', 'Body and Painting'), ('Suspension Repair', 'Suspension Repair')], max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.customer')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderMiscellaneous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miss_code', models.CharField(choices=[('CON', 'Consumables'), ('KLM', 'Kilometers')], max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('work_order_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_orders.workordersegment')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderServiceLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_service', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('labor_type', models.CharField(choices=[('REP', 'Repair'), ('MNT', 'Maintenance'), ('BNP', 'Body and Paint')], max_length=20)),
                ('service_man_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.serviceman')),
                ('work_order_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_orders.workordersegment')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=30)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('work_order_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_orders.workordersegment')),
            ],
        ),
    ]
