# Generated by Django 5.0.7 on 2024-08-05 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_work', models.CharField(choices=[('Maintenance', 'Maintenance'), ('Engine Repair', 'Engine Repair'), ('Transmission Repair', 'Transmission Repair'), ('Body and Painting', 'Body and Painting'), ('Suspension Repair', 'Suspension Repair')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miss_code', models.CharField(choices=[('CON', 'Consumables'), ('KLM', 'Kilometers')], max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('work_order_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misc', to='work_orders.segment')),
            ],
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_service', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('labor_type', models.CharField(choices=[('REP', 'Repair'), ('MNT', 'Maintenance'), ('BNP', 'Body and Paint')], max_length=20)),
                ('service_man_number', models.ManyToManyField(to='data.serviceman')),
                ('work_order_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor', to='work_orders.segment')),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=30)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('work_order_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_part', to='work_orders.segment')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(blank=True, choices=[('Credit', 'Credit'), ('Cash', 'Cash')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invoiced', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.customer')),
            ],
        ),
        migrations.AddField(
            model_name='segment',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment', to='work_orders.workorder'),
        ),
    ]
