# Generated by Django 5.0.7 on 2024-08-06 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labor',
            name='service_man_number',
        ),
        migrations.AddField(
            model_name='labor',
            name='service_man_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_man', to='data.serviceman'),
            preserve_default=False,
        ),
    ]
