# Generated by Django 5.0.7 on 2024-08-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0002_workorder_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='invoiced',
            field=models.BooleanField(default=False),
        ),
    ]
