# Generated by Django 5.0.7 on 2024-08-08 03:23

import work_orders.models_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0002_remove_labor_service_man_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labor',
            name='end_time',
            field=models.TimeField(validators=[work_orders.models_validators.end_work_validator]),
        ),
        migrations.AlterField(
            model_name='labor',
            name='start_time',
            field=models.TimeField(validators=[work_orders.models_validators.start_work_validator]),
        ),
    ]
