# Generated by Django 5.0.7 on 2024-08-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0003_alter_labor_end_time_alter_labor_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneous',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
