# Generated by Django 5.0.7 on 2024-08-04 10:19

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0004_workorder_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelManagers(
            name='workorder',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='workorder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
