# Generated by Django 5.0.7 on 2024-08-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0004_miscellaneous_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
