# Generated by Django 5.0.7 on 2024-08-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0005_workorder_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='labor_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='mics_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='spare_part_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
