# Generated by Django 5.0.7 on 2024-08-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0006_workorder_labor_price_workorder_mics_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='labor_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='mics_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='spare_part_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
