# Generated by Django 5.0.7 on 2024-08-18 18:33

import work_orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0007_alter_workorder_labor_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[work_orders.models.Segment.calculate_seg_total]),
        ),
    ]
