# Generated by Django 5.0.7 on 2024-08-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0008_segment_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='description_work',
            field=models.TextField(blank=True, null=True),
        ),
    ]
