# Generated by Django 5.0.7 on 2024-07-24 03:21

import data.my_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brand',
            new_name='make',
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Gray', 'Gray'), ('Silver', 'Silver'), ('Red', 'Red'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Other', 'Other')], max_length=55),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, choices=[('Diesel', 'Diesel'), ('Gasoline', 'Gasoline'), ('Gas', 'Gas'), ('Hybrid', 'Hybrid')], max_length=55),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(choices=[('Bulgaria', 'Bulgaria'), ('Albania', 'Albania'), ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'), ('Greece', 'Greece'), ('Kosovo', 'Kosovo'), ('North Macedonia', 'North Macedonia'), ('Montenegro', 'Montenegro'), ('Romania', 'Romania'), ('Serbia', 'Serbia'), ('Turkey', 'Turkey'), ('Croatia', 'Croatia'), ('Slovenia', 'Slovenia')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[data.my_validators.credit_limit_validator]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vat',
            field=models.IntegerField(validators=[data.my_validators.vat_number_validator]),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='phone_number',
            field=models.IntegerField(max_length=20, validators=[data.my_validators.phone_number_validator]),
        ),
        migrations.AlterField(
            model_name='serviceman',
            name='phone_number',
            field=models.IntegerField(max_length=20, validators=[data.my_validators.phone_number_validator]),
        ),
        migrations.AlterField(
            model_name='serviceman',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[data.my_validators.rating_validator]),
        ),
    ]
