# Generated by Django 5.0.7 on 2024-08-13 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SparePart',
            new_name='SparePartWarehouse',
        ),
    ]
