# Generated by Django 5.0.7 on 2024-07-29 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='data.customer'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='part_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
