# Generated by Django 5.0.7 on 2024-08-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='flb',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
