# Generated by Django 5.1.1 on 2024-11-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_customer_flb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='car',
            name='make',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
    ]
