# Generated by Django 5.0.7 on 2024-07-25 16:56

import data.my_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_brand_car_make_alter_car_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='phone_number',
            field=models.IntegerField(validators=[data.my_validators.phone_number_validator]),
        ),
        migrations.AlterField(
            model_name='serviceman',
            name='phone_number',
            field=models.IntegerField(validators=[data.my_validators.phone_number_validator]),
        ),
    ]
