# Generated by Django 5.1.1 on 2024-11-22 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_cartype_remove_car_engine_remove_car_make_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_indication',
            field=models.ForeignKey(default=0.07575757575757576, on_delete=django.db.models.deletion.CASCADE, to='data.cartype'),
            preserve_default=False,
        ),
    ]
